# Generated by Django 5.2.5 on 2025-09-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examtype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
