# Generated by Django 5.2.5 on 2025-09-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logical', '0002_tbl_examtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_name', models.CharField(max_length=50)),
                ('examination_mark', models.CharField(max_length=50)),
                ('examination_qno', models.CharField(max_length=50)),
                ('examination_time', models.CharField(max_length=50)),
                ('examination_status', models.IntegerField(default=0)),
                ('examination_date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('examtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logical.tbl_examtype')),
            ],
        ),
    ]
