# Generated by Django 5.2.5 on 2025-09-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logical', '0003_tbl_examination'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logical.tbl_examination')),
            ],
        ),
    ]
