# Generated by Django 5.1.6 on 2025-10-22 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_alter_tbl_userregistration_user_photo'),
        ('Interview', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration'),
        ),
    ]
