# Generated by Django 5.1.6 on 2025-10-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0004_alter_interviewresponse_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='inter_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript')], max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
