# Generated by Django 5.2.5 on 2025-10-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_answer_question_quiztype_userresponse_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztype',
            name='time_per_question',
            field=models.IntegerField(default=60),
        ),
    ]
