# Generated by Django 5.2.5 on 2025-10-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_quiztype_time_per_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userresponse',
            options={'verbose_name': 'User Response', 'verbose_name_plural': 'User Responses'},
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
