# Generated by Django 5.2.5 on 2025-10-14 16:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_userresponse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted', models.BooleanField(default=False)),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='quiztype',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiztype',
            name='has_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiztype',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='quiztype',
            name='time_per_question',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz_type', 'number')},
        ),
        migrations.AddConstraint(
            model_name='quiztype',
            constraint=models.CheckConstraint(condition=models.Q(('has_expiry', False), models.Q(('has_expiry', True), ('start_time__isnull', False), ('end_time__isnull', False)), _connector='OR'), name='expiry_fields_required_if_has_expiry'),
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='quiz_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quiztype'),
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userquizattempt',
            unique_together={('user', 'quiz_type')},
        ),
    ]
