# Generated by Django 5.2.5 on 2025-10-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userquizattempt_quiztype_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quiztype',
            name='expiry_fields_required_if_has_expiry',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiztype',
            name='time_per_question',
            field=models.IntegerField(default=60),
        ),
    ]
