# Generated by Django 5.2.5 on 2025-09-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_placement_drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_details', models.CharField(max_length=50)),
                ('placement_companyname', models.CharField(max_length=50)),
                ('placement_minmark', models.CharField(max_length=50)),
                ('placement_backlog', models.CharField(max_length=50)),
                ('placement_file_doc', models.FileField(upload_to='Assets/jobpost/')),
                ('placement_lastdate', models.DateField()),
                ('placement_status', models.IntegerField(default=0)),
            ],
        ),
    ]
