# Generated by Django 5.2.5 on 2025-09-10 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_placement_drive'),
        ('logical', '0005_tbl_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examinationbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField(default=0)),
                ('examinationbody_status', models.IntegerField(default=0)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logical.tbl_examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_placement_drive')),
            ],
        ),
    ]
