# Generated by Django 5.2.5 on 2025-09-10 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_examinationbody'),
        ('logical', '0005_tbl_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examinationanswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinationanswers_statusq', models.IntegerField(default=0)),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='logical.tbl_options')),
                ('examinationbody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_examinationbody')),
                ('myanswer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myanswer', to='logical.tbl_options')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logical.tbl_questions')),
            ],
        ),
    ]
