# Generated by Django 5.2.5 on 2025-09-10 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_timmer'),
        ('Guest', '0006_alter_tbl_userregistration_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_placement_drive',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration'),
        ),
    ]
