# Generated by Django 5.2.5 on 2025-09-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_placement_drive_user'),
        ('Guest', '0006_alter_tbl_userregistration_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_examinationbody',
            name='examination',
        ),
        migrations.RemoveField(
            model_name='tbl_examinationbody',
            name='examinationbody_status',
        ),
        migrations.RemoveField(
            model_name='tbl_examinationbody',
            name='total_marks',
        ),
        migrations.AlterField(
            model_name='tbl_examinationbody',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration'),
        ),
    ]
