# Generated by Django 5.2.5 on 2025-09-11 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_remove_tbl_examinationbody_examination_and_more'),
        ('Guest', '0006_alter_tbl_userregistration_user_photo'),
        ('logical', '0005_tbl_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_examinationbody',
            name='examination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logical.tbl_examination'),
        ),
        migrations.AddField(
            model_name='tbl_examinationbody',
            name='examinationbody_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_examinationbody',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_examinationbody',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration'),
        ),
        migrations.AlterField(
            model_name='tbl_examinationbody',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_placement_drive'),
        ),
    ]
