# Generated by Django 5.2.5 on 2025-08-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_address', models.TextField()),
                ('user_city', models.CharField(max_length=50)),
                ('user_state', models.CharField(max_length=50)),
                ('user_mark10', models.CharField(max_length=30)),
                ('user_mark12', models.CharField(max_length=30)),
                ('user_mark', models.CharField(max_length=30)),
                ('user_photo', models.FileField(upload_to='Userdocs/')),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
    ]
