# Generated by Django 5.2.5 on 2025-08-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_userregistration',
        ),
    ]
