# Generated by Django 5.2.5 on 2025-09-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_userregistration',
            name='user_backlog',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
