# Generated by Django 5.2.5 on 2025-09-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_userregistration',
            name='user_photo',
            field=models.FileField(null=True, upload_to='Userdocs/'),
        ),
    ]
